
@startuml

skinparam actorStyle awesome
skinparam packageStyle rectangle

:Customer: <<Human>>
:Chef: <<Human>>
:Server: <<Human>>
:Boss: <<Human>>

package Restaurant{
usecase "Eat Food"
usecase "Orders"
usecase "Pay"
usecase "Eat Food"
}

package GUI{
usecase "Appetizers"
usecase "Main Dish"
usecase "Desserts"
usecase "Drinks"
}

note "Chef will recommend\nwhat to add or remove\nfrom the menu." as N1
note "The Database will recommend\nwhat food to eat without \nthe allergen from the menu." as N3
note "Customer will order\nand specify what \nthey are allergic from." as N2
note "Chef will make food" as N4
note "Server serves the \nfood to the Customer" as N5

:Boss: -> (Database)
:Customer: .. N2
N2 .. (Orders)

:Customer: -> Restaurant
(Orders) -> (Menu)
(Database) <--> (Menu)
(Menu) --> Chef
GUI <-- (Menu)

Database .. N3
N3 .. Menu
:Boss: .. N1
N1 .. :Chef:
Chef --> Server

Server --> Customer
:Chef: --> :Boss:
Menu .. N4
N4 .. Chef
Server .. N5
N5 .. Customer


@enduml