@startuml

skinparam actorStyle awesome
skinparam packageStyle rectangle
skinparam backgroundColor tomato
skinparam object{
BackgroundColor white
BorderColor maroon
FontColor maroon
ArrowColor business
FontStyle bold
AttributeIconSize 0
}
hide empty members

skinparam actorStyle awesome

:Customer: <<Human>>
:GUI: <<System>>
:Database: <<System>>

usecase "Order"
usecase "Prints Menu without Allergy"
usecase "Pay"
usecase "Prints Bill"
usecase "End"

package Menu {
    usecase "Appetizers"
    usecase "Main Dish"
    usecase "Dessert"
    usecase "Beverage"
}

Order --> (GUI)

Pay --> End

(Start) --> Customer
Customer --> Order
Order <-- (Prints Menu without Allergy)

Database <--> (GUI)
Database <--> Menu

(Prints Menu without Allergy) <-- (GUI)

(Prints Menu without Allergy) --> (Prints Bill)
(Prints Bill) --> Pay

note top of (GUI): Gets Necessary Data

note left of Menu: Allergen:\nSeafood\nNuts\nDairy

@enduml
