@startuml

skinparam actorStyle awesome
skinparam packageStyle rectangle

:Customer: <<Human>>
:Chef: <<Human>>
:Server: <<Human>>
:GUI: <<Program>>
package Restaurant{
usecase "Order Food"
usecase "Eat Food"
usecase "Serves Food"
}
package Kitchen{
usecase "Ready Food"
}
usecase "Pay"

note "After eating, the \ncustomer will pay" as N1
note "Customer will be ordering \nthrough the GUI" as N2
note "Chef will then \nreceive the order" as N3
note "After readying the food\n the server serves the food\nto the customer" as N4
Customer ---> GUI
GUI ->(Order Food): "Customer specifies if \nhe/she has allergies for\n the program to filter"
GUI --> N2
(Order Food) --> Chef
Chef --> N3
Chef --> (Ready Food)
(Ready Food) --> Server
Server --> (Serves Food)
Server --> N4
(Serves Food) --> Customer
Customer ---> (Eat Food)
(Eat Food) ---> (Pay)
(Pay) --> N1
@enduml